function B = B_Mat_gen(in1)
%B_MAT_GEN
%    B = B_MAT_GEN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    02-Jan-2019 17:11:43

B = reshape([0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[8,5]);
