function G = G_Mat_gen(in1)
%G_MAT_GEN
%    G = G_MAT_GEN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    02-Jan-2019 17:11:42

phi1 = in1(7,:);
phi2 = in1(8,:);
th2 = in1(5,:);
th3 = in1(6,:);
G = [0.0;0.0;9.81e2./2.0e1;0.0;cos(phi1).*cos(th2).*7.3575;cos(phi2).*cos(th3).*(9.81e2./4.0e2);sin(phi1).*sin(th2).*(-7.3575);sin(phi2).*sin(th3).*(-9.81e2./4.0e2)];
